image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.2"
  ANDROID_SDK_TOOLS: "6514223"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

  - export ANDROID_HOME="${PWD}/android-home"
  - install -d $ANDROID_HOME

  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip

  - pushd $ANDROID_HOME
  - unzip -d cmdline-tools cmdline-tools.zip
  - popd
  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/tools/bin/

  - sdkmanager --version

  - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true
  - sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools"
  - sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS}"

  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/
    - android-home/cmdline-tools

stages:
  - build
  - test
  - qa
  - deploy

.only_on_develop_and_master: &only_on_develop_and_master
  only:
    - master
    - develop

build:
  stage: build
  <<: *only_on_develop_and_master
  interruptible: true
  script:
    - ./gradlew --stop
    - ./gradlew clean assembleDebug --stacktrace
  artifacts:
    expire_in: 4 days
    paths:
      - app/build/outputs/

test:
  stage: test
  <<: *only_on_develop_and_master
  interruptible: true
  script:
    - ./gradlew testDebug
  artifacts:
    paths:
      - app/build/reports/tests/


qa:
  stage: qa
  <<: *only_on_develop_and_master
  interruptible: true
  script:
    - ./gradlew lintDebug


deploy:
  interruptible: true
  <<: *only_on_develop_and_master
  stage: deploy
  script:
    - echo "Deployed successfully!"

